### ISSUE TITLE
行内公式的识别问题

### ISSUE THREAD

**Issue by guba-exe** [yfzhao20/Shift-IM-for-VSCode#3]
用这个插件有一段时间了，十分感谢作者的付出。但是有一个问题就是，同一行内有其他文字时，像\$ \$的公式不会被识别。似乎只有当这一行有且只有公式\$\$时才会识别。

\$\$  
上面这行可以识别 

\$\$  
...  
\$\$  
上面也可以识别  

abc\$ \$  
这样不能被识别

**Comment by yfzhao20** [comment]
感谢反馈！我这里好像没有问题：
![image](https://user-images.githubusercontent.com/80528249/166644884-4cf4591a-2dba-4a87-a6c2-39b1cb3032ee.png)

推测一下：
1. 这时候有高亮吗？如果没有高亮，那么也应该不会有预览，因为用的是同一套识别系统。
   另外，vscode 内置的 markdown math 插件要求必须在文字之后打一个空格，然后输公式：
   ![image](https://user-images.githubusercontent.com/80528249/166645283-a46116d0-15a0-46be-9555-2659e3fa9458.png)
   如果没有空格就不认：
   ![image](https://user-images.githubusercontent.com/80528249/166645337-e7e72bcc-11ce-4cc8-a529-eae81b6f5de5.png)
   然后安装 markdown All In One 插件，就可以在文字后紧跟数学公式了：
   ![image](https://user-images.githubusercontent.com/80528249/166645640-69f63031-cb4f-450c-99c0-6c2c2a8be01c.png)
   装完记着重启vscode一下~

2. 如果仍然不行，禁用其他扩展试试（除了 HyperScopes Booster）；
3. 如果还不行，可以发下源文件吗，我来调试一下

**Comment by guba-exe** [comment]
感谢 经过调试以后确认是Markdown+math插件问题，关闭以后正常，很抱歉打扰您

**Comment by yfzhao20** [comment]
没事！解决了就好😃
